theme: jekyll-theme-minimal
title: Locaweb Servidores .NET SDK Client
description: Locaweb Servidores API Client SDK for .NET projects
logo: https://raw.githubusercontent.com/guibranco/locaweb-servidores-sdk-dotnet/main/logo.png
show_downloads: true
